apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer   
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32223